### ISSUE TITLE
Don't use IE for documentation

### ISSUE THREAD

**Issue by malankriel** [AutoActuary/deploy-scripts#29]
Most clients have IE as their default browser:
![image](https://user-images.githubusercontent.com/51300197/95732290-e313b980-0c80-11eb-8c51-6209d3611622.png)

And the documentation doesn't sit well there :). It works well on Chrome and Edge

Most users have Chrome installed (although not guaranteed).
Sanlam has Edge on their server machines. Old Mutual don't

So my recommendation (if it makes sense):
 1. Prefer Chrome
 2. Prefer Edge

**Comment by rudolfbyker** [comment]
Not as clean as I thought. We need to keep a list of paths where we expect to find the browser `.exe` files on the disk, and loop through them until we find one that works. If the browser is installed to a custom location, it will not work.

Then there is the additional problem that [`webbrowser.open()`](https://docs.python.org/3.8/library/webbrowser.html#webbrowser.open), which we used, always opens the default browser (bad), but it does not block (good). The new way of doing it calls [`open`](https://docs.python.org/3.8/library/webbrowser.html#webbrowser.controller.open) on a Browser Controller object, which opens the browser we want (good) but blocks (bad).

See my last commit to understand what I mean by "block".

**Comment by rudolfbyker** [comment]
Sorted.
