### ISSUE TITLE
Decompile just stopped working

### ISSUE THREAD

**Issue by malankriel** [AutoActuary/deploy-scripts#30]
![image](https://user-images.githubusercontent.com/51300197/95740228-6b4b8c00-0c8c-11eb-95b0-7ac4c5ffe56a.png)

Was working fine, I've just updated another Inputs workbook's vba code (using RunnerInputs-replace-workbook-vba.bat) and now it stopped working again
I've clear the temp folder, restarted the computer, but still get this error

**Comment by malankriel** [comment]
I've reverted to using the vbs script for now and it is working 👍 
![image](https://user-images.githubusercontent.com/51300197/95740867-8a96e900-0c8d-11eb-87d1-fbd8c47dd8e4.png)

**Comment by heetbeet** [comment]
I think I know the issue, we replaced the temp file creation thingy that was deprecated with a non-deprecated one. I think I should just revert that change and go with the deprecated function for now and make a note.

**Comment by heetbeet** [comment]
That is also such a strange filepath

**Comment by heetbeet** [comment]
Fix is in 5806aeb

**Comment by malankriel** [comment]
> That is also such a strange filepath

@heetbeet yes, when calling my temp folder from Python (and R I think) it takes us to that weird folder, but `%Temp%` takes me to `C:\Users\malan\AppData\Local\Temp`.

**Comment by malankriel** [comment]
Sorted now, thanks @heetbeet !
