### ISSUE TITLE
VCS case sensitivity

### ISSUE THREAD

**Issue by malankriel** [AutoActuary/deploy-scripts#31]
All checks (for tables, variables etc should be case insensitive)

When I call the listObject `vcsMetadata`, I get this error:
![image](https://user-images.githubusercontent.com/51300197/95787159-39144b80-0cd9-11eb-9819-6e4a21eae59d.png)
and it disappears when changing the name to `VcsMetadata`

The Table, Column and OldNames checks should also be case insensitive.
If the user changes the `VarName` to `Varname`, it shouldn't see it as a new variable:
![image](https://user-images.githubusercontent.com/51300197/95787586-1a628480-0cda-11eb-9f6f-691228899978.png)

**Comment by rudolfbyker** [comment]
@malankriel If the case does not matter, which case should be used when exporting / importing? Or is it acceptable to always convert everything to lower case?

**Comment by malankriel** [comment]
Ideally when importing the user should have the actual casing that was used in the "master"
But I understand that can result in version control issues due to changes in case

**Comment by malankriel** [comment]
Because we don't want `VariableSetName` to be imported as `variablesetname` or `VARIABLESETNAME`. If it doesn't exist
