### ISSUE TITLE
vcs system needs support for named ranges used as a table

### ISSUE THREAD

**Issue by malankriel** [AutoActuary/deploy-scripts#37]
For the configuration (user input tables), we mostly used a named range with the header in the first row of the table.

Here we will usually only need to only version control the headers.

**Comment by rudolfbyker** [comment]
This should be two separate issues.

**Comment by rudolfbyker** [comment]
Extraction of VCS header data from named ranges is complete. Next up: Importing it back into the named ranges.

**Comment by malankriel** [comment]
Here we'll need to be careful when adding a column to the start or end. We need to either
 - add column before last column so named range expand
 - expand the named range using resize or something similar

Second option is better but edge case is when named ranges aredl dynamic (but we shouldn't be using them because they are bad).

**Comment by rudolfbyker** [comment]
Let's definitely not support dynamic named ranges... Is there a quick way to detect whether it's dynamic? Then we can simply `raise NotImplementedError`

**Comment by malankriel** [comment]
? thisworkbook.names("HierarchyTree").RefersTo
=OFFSET(HierarchyTreeStart,1,1,HierarchyTreeRowsCount,HierarchyTreeColsCount)

The RefersTo Property of the name with start with `=OFFSET(`

**Comment by malankriel** [comment]
As opposed to a reference to a range:

```
? thisworkbook.names("RunDate").RefersTo
=RunControl!$D$7
```

**Comment by malankriel** [comment]
> ```
> ? thisworkbook.names("HierarchyTree").RefersTo
> =OFFSET(HierarchyTreeStart,1,1,HierarchyTreeRowsCount,HierarchyTreeColsCount)
> ```
> 
> The RefersTo Property of the name with start with `=OFFSET(`
> 
> ```
> ? thisworkbook.names("TableLookupLists").RefersTo
> =IF(Tables!L$5="valnType",valnTypes,IF(Tables!L$5="varName",VarNames,IF(ISNUMBER(MATCH(Tables!L$5,hLevelNames[Name],0)),UniqueHNamesLookup,NoLookupString)))
> ```

@rudolfbyker just note the above, it's not only OFFSET but any named range including a function in the RefersTo property.
