### ISSUE TITLE
On import, ensure vcs tables exist, if not add them

### ISSUE THREAD

**Issue by malankriel** [AutoActuary/deploy-scripts#50]
When importing tables, we should ensure:
 - VcsTableHeaderMetadata table exist, with the appropriate columns
 - the new git commit table exists, with appropriate columns

If neither exists, add a sheet called VCS, make it very hidden and add the missing table to the end of the sheet.
This can also happen through patches in the runner inputs side, but just let me know then 👍 / create issue in runner-inputs

**Comment by rudolfbyker** [comment]
This will require a cleverer make_table function, with the ability to add tables side by side. The implementation at #47 creates a new sheet for each table.
